upstream user_services {
    server user-service-1:8002 max_fails=3 fail_timeout=30s;
    server user-service-2:8002 max_fails=3 fail_timeout=30s;
}

server {
    listen 9002;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout 5s;
    proxy_read_timeout 10s;

    location / {
        proxy_pass http://user_services/;
    }
}