server {
    listen 8000;
    server_name localhost;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 5s;
    proxy_read_timeout 10s;

    location /auth/ {
        proxy_pass http://auth-lb:9001/;
    }

    location /user/ {
        proxy_pass http://user-lb:9002/;
    }

    location /order/ {
        proxy_pass http://order-lb:9003/;
    }
}